### PR TITLE
Add rangevalue complication

### PR DESCRIPTION
**Pull request by grimpy**
Add a range complication, this allows to see the time remaining in the current prayer.

### CODE REVIEW

**Comment by grimpy** [comment]
image

Example image

**Review by tazzix — CHANGES_REQUESTED** [review]
Please resolve the conflict, also please explain what is the purpose of this change? What are the three times?

**Comment by grimpy** [comment]
I added some descriptions in the OT and underneath the picture post

**Comment by tazzix** [comment]
> I added some descriptions in the OT and underneath the picture post

Thank you so much, this can be really useful, but even more if this is configurable from the configuration screen. If you can do that perfect, otherwise I will update the PR before merging it.

**Comment by grimpy** [comment]
> Thank you so much, this can be really useful, but even more if this is configurable from the configuration screen. 

What kind of configuration are you expecting? 
> If you can do that perfect, otherwise I will update the PR before merging it.

I'm not really experienced with kotlin/android ui development so if it's not too much effort for you I would appreciate that

**Comment by tazzix** [comment]
> > Thank you so much, this can be really useful, but even more if this is configurable from the configuration screen.
> 
> What kind of configuration are you expecting?
> 
> > If you can do that perfect, otherwise I will update the PR before merging it.
> 
> I'm not really experienced with kotlin/android ui development so if it's not too much effort for you I would appreciate that

Instead of configuration, what can be done is to provide two different complications instead of just one, because your PR removes my complication and that is the way I want to keep my watch face. So if you implement your way of showing it as a different complication, then users can chose one view or the other.

**Comment by grimpy** [comment]
That sounds good, does that mean it needs to be registered as a seperate complications provider in the manifest?

**Comment by tazzix** [comment]
> That sounds good, does that mean it needs to be registered as a seperate complications provider in the manifest?

Not sure, I have not done that before, will try to look at an example

**Comment by grimpy** [comment]
I've split them in two separated services to accommodate this.

**Comment by tazzix** [comment]
> I've split them in two separated services to accommodate this.

Thank you so much, let me test this in a day or two and then I will merge it.

**Comment by grimpy** [comment]
Any update on this?

**Review by tazzix — APPROVED** [review]

**Pull request merged**
